version: "3.8"

services:

  maven:
    image: maven
    restart: "no"
    volumes:
      - ".:/tmp/backend"
    command:
      - "mvn"
      - "-f"
      - "/tmp/backend"
      - "clean"
      - "package"

  mongo:
    image: 'mongo:4.4.0-rc8-bionic'
    restart: always
    volumes:
      - "mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  openjdk:
    image: openjdk
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./target/backend-0.0.1-SNAPSHOT.jar:/opt/backend/backend.jar:ro"
    command:
      - "java"
      - "-jar"
      - "/opt/backend/backend.jar"

volumes:
  mongo:
